# Generated by Django 2.1.7 on 2020-07-07 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceproviderprofile',
            fields=[
                ('serviceproviderprofileid', models.AutoField(primary_key=True, serialize=False)),
                ('regno', models.CharField(default='', max_length=6)),
                ('name', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(default='', max_length=12)),
                ('estyear', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('address2', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=50)),
                ('statename', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=70)),
                ('zipf', models.CharField(default='', max_length=6)),
                ('bio', models.CharField(default='', max_length=750)),
                ('email', models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
