# Generated by Django 2.1.7 on 2020-07-07 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_serviceproviderprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeid', models.AutoField(primary_key=True, serialize=False)),
                ('prfilepic', models.ImageField(default='', upload_to='home/employeeprofile')),
                ('firstname', models.CharField(default='', max_length=255)),
                ('middlename', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('dob', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=12)),
                ('address', models.CharField(default='', max_length=255)),
                ('address2', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=50)),
                ('statename', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=70)),
                ('zipf', models.CharField(default='', max_length=6)),
                ('bio', models.CharField(default='', max_length=750)),
                ('charges', models.CharField(default='', max_length=6)),
                ('worktype', models.CharField(default='', max_length=50)),
                ('vacantstatus', models.CharField(default='', max_length=6)),
                ('serviceproviderprofileid', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='properties.Serviceproviderprofile')),
            ],
        ),
    ]
