# Generated by Django 2.1.7 on 2020-07-07 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0003_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roommateprofile',
            fields=[
                ('roommateprofileid', models.AutoField(primary_key=True, serialize=False)),
                ('prfilepicfile', models.ImageField(default='', upload_to='home/roommateuserprofile')),
                ('firstname', models.CharField(default='', max_length=255)),
                ('middlename', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('dob', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=12)),
                ('address', models.CharField(default='', max_length=255)),
                ('address2', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=50)),
                ('statename', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=70)),
                ('zipf', models.CharField(default='', max_length=6)),
                ('smoking', models.CharField(default='', max_length=6)),
                ('alchohal', models.CharField(default='', max_length=6)),
                ('nonvegitarian', models.CharField(default='', max_length=6)),
                ('earlybird', models.CharField(default='', max_length=6)),
                ('bio', models.CharField(default='', max_length=750)),
                ('rent', models.CharField(default='', max_length=15)),
                ('area', models.CharField(default='', max_length=15)),
                ('propertytype', models.CharField(default='', max_length=7)),
                ('mainimage', models.ImageField(default='', upload_to='properties/roommateprofilepropertyimages')),
                ('maxtanent', models.CharField(default='', max_length=2)),
                ('livingtanent', models.CharField(default='', max_length=15)),
                ('expecteddescriptionofguy', models.CharField(default='', max_length=750)),
                ('email', models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
