# Generated by Django 2.1.7 on 2020-07-07 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_roommateprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roommateprofilepropimages',
            fields=[
                ('imageid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='properties/roommateprofilepropertyimages')),
                ('propertytype', models.CharField(default='', max_length=10)),
                ('roommateprofileid', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='properties.Roommateprofile')),
            ],
        ),
    ]
